on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: vgcontainer.azurecr.io
        username: ${{ secrets.acr_vgcontainer_username }}
        password: ${{ secrets.acr_vgcontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t vgcontainer.azurecr.io/vgdocker-img:${{ github.sha }}
        docker push vgcontainer.azurecr.io/vgdocker-img:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: vgdocker
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "vgcontainer.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.acr_vgcontainer_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.acr_vgcontainer_password }}",
              "slotSetting": false
            }            
          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: vgdocker
        images: vgcontainer.azurecr.io/vgdocker-img:${{ github.sha }}
